### ISSUE TITLE
Purpose of this CustomEvents?

### ISSUE THREAD

**Issue by khex** [ionic-team/ionic-conference-app#1251]
In file `src/app/providers/user-data.ts` on line 31, 35, 42 & 50 there are code that creates **CustomEvents** like

```
    ...
    this.setUsername(username);
    return window.dispatchEvent(new CustomEvent('user:login'));
    ...
```
Can you tell me purpose of this events?

**Comment by biesbjerg** [comment]
@khex it makes it possible for other parts of the app to listen for events, in this case used to reflect that the user has logged in:

https://github.com/ionic-team/ionic-conference-app/blob/024450f4a820576c5366d90956551372fd891d36/src/app/app.component.ts#L105-L107

**Comment by brandyscarney** [comment]
@biesbjerg is correct. We added it to replace our old Events service in v4: https://github.com/ionic-team/ionic/blob/master/BREAKING.md#events
