### ISSUE TITLE
Add RouteConfig working example

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-conference-app#142]
Request for a RouteConfig example in the conf app. Thoughts @adamdbradley ?

**Comment by lordgreg** [comment]
:+1:

**Comment by matt4446** [comment]
+1 
this would be my preference in controlling the app state and understanding the navigation hierarchy of the app (making it easier to visualize and understand). Examples using the router directives (plus route parameters) instead of the component model controlling the routing would be advantageous too.

**Comment by cyprusglobe** [comment]
:+1:

**Comment by adamdbradley** [comment]
I'd like to hold off until ng2 router solidifies their upcoming changes first. Additionally, Ionic routing needs to be updated to work on tabs, which is waiting on the ng2 router updates.

**Comment by adamdbradley** [comment]
This is a simple demo of using Ionic with RouterConfig: https://github.com/driftyco/ionic/blob/2.0/ionic/components/nav/test/routing/index.ts#L47

**Comment by ace-han** [comment]
I think an working example is not enough. 
A working example with `auth` mechanism is much more appropriate

Like 
* `ng1`: http://stackoverflow.com/questions/22537311/angular-ui-router-login-authentication
* third party plugin: https://auth0.com/blog/2016/02/18/ionic-2-authentication-how-to-secure-your-mobile-app-with-jwt/

To be specific, example that suits below requirement will be much better
1. `RouteConfig` in some central files for easy management
2. Secret section(s) in the same page

Thx.

**Comment by jgr3go** [comment]
I think to add to @ace-han's list would be a third item:

3. Force redirect to login on app start, all pages are only accessible if logged in. 

This is a much more common paradigm for apps than for websites, which is my main issue with the [auth0](https://auth0.com/blog/2016/02/18/ionic-2-authentication-how-to-secure-your-mobile-app-with-jwt/) example -- it's very likely that apps would want to force uses to log in before doing anything in their app. ngSwitch's on public and private data can't really solve that workflow.

**Comment by warner-pinz** [comment]
@adamdbradley @brandyscarney the tutorial link is dead
https://github.com/driftyco/ionic/blob/2.0/ionic/components/nav/test/routing/index.ts#L47

Please share some working examples. Thanks

**Comment by brandyscarney** [comment]
The Angular router is disabled with the latest release (beta 7). From the changelog:

> The Angular router is currently under heavy development and refactoring. As a result of this, Angular’s router is currently disabled within Ionic. If your app requires use of the router we recommend waiting until a future release of Ionic when Angular has completed work on the new router. However, this does not affect Ionic’s navigation system and it continues to work with the same API from previous versions.

**Comment by brandyscarney** [comment]
@warner-pinz I updated Adam's comment to point to the correct link. We recently ([#6491](https://github.com/driftyco/ionic/issues/6491)) renamed the `ionic` repo to `src` so if you see any links using `ionic` they need to be changed to `src`. :smile: We'll update these as it is brought to our attention.

Here is the correct link to the Router example, keep in mind this does not work with `beta 7` of Ionic:
https://github.com/driftyco/ionic/blob/2.0/src/components/nav/test/routing/index.ts#L58

**Comment by kingkarki** [comment]
@brandyscarney is routing on ionic 2 back yet? All the links above are dead.

**Comment by pimenteljchristopher** [comment]
all dead @brandyscarney  find one if you want i could setp a working link hahah

**Comment by supgeek-rod** [comment]
@adamdbradley page 404 https://github.com/driftyco/ionic/blob/2.0/src/components/nav/test/routing/index.ts#L58

**Comment by b264** [comment]
Is there still no example code?

**Comment by 5im0n** [comment]
👍 to add DeepLinkConfig for PWA.

To my mind with deepLinkConfiguration, setting the rootPage is irrevelant.

**Comment by brandyscarney** [comment]
DeepLinker documentation is here: http://ionicframework.com/docs/v2/api/navigation/DeepLinker/

Updates to DeepLinker in the framework are happening on this branch: https://github.com/driftyco/ionic/tree/3.0

We're working on adding it on this branch, but it has a lot of dependency changes: https://github.com/driftyco/ionic-conference-app/tree/lazy-load

**Comment by brandyscarney** [comment]
I'm going to close this since `master` has examples using Angular's router. Thanks.
