### ISSUE TITLE
Issues running

### ISSUE THREAD

**Issue by genu** [ionic-team/ionic-conference-app#1684]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

![image](https://user-images.githubusercontent.com/928780/120121270-7518f580-c170-11eb-945e-150b2e2df71d.png)

**Expected behavior:**
This project template should be able to run out of the box since its an option in the official CLI.

**Steps to reproduce:**
1. `ionic start sample`
2. Select this as a starting template
3. run `yarn start`

**Ionic info:**
Ionic:

   Ionic CLI                     : 6.16.1 
   Ionic Framework               : @ionic/angular 5.6.8
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                  : 8.3.29
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.17.0 
   npm    : 6.14.13
   OS     : macOS Big Sur

**Comment by dtarnawsky** [comment]
Closing as this is not for the conference app
