### ISSUE TITLE
get error on    ionic g page xxxxx

### ISSUE THREAD

**Issue by elmor34** [ionic-team/ionic-conference-app#1753]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When try to generate a page I get the message :

> ng generate page pages/site-menu --project=app
> An unhandled exception occurred: Schematic "page" not found in collection "@angular-eslint/schematics".
> See "/private/var/folders/p9/y5g8_4d12vq_msfn0xsvh0k40000gp/T/ng-Cu2ngL/angular-errors.log" for further details.
> [ERROR] Could not generate page.

A problem in angular.json file as:

>  "cli": {
>     "defaultCollection": "@angular-eslint/schematics"
>   },

**Comment by venukommu** [comment]
Hello @elmor34,
Did you find any solution for the above issue ?

We are also getting same issue while we are trying to generate the service/page, not sure how to fix it. Let us know if there is any solution, otherwise we move back to different template.

**Comment by venukommu** [comment]
I have fixed this issue by changing schematic to angular-toolkit in the angular.json

`"cli": {
    "defaultCollection": "@ionic/angular-toolkit"
  },`
