### ISSUE TITLE
Show Schedule for Multiple Days

### ISSUE THREAD

**Issue by thomastthai** [ionic-team/ionic-conference-app#189]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### Short description of the problem:

Currently only shows one day for the conference. I recommend adding data for another day and change the loop to show the second day under Schedule as well.
#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which branch are you on?** master or typescript

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by NexusInk** [comment]
Currently creating a starter based on this theme so I come across this "issue"...
*Aks myself* Am I dim for building out a larger data set for this demo?
*Answer to ditto* No -of course not...

Be that as it may, I will have posted a the starter theme by Sunday 29th of May on the Ionic Market, embellished with bells and whistles and coffee-making capabilities for the awesome price of almost expensive.

Would be happy to provide the data set, only that it is built on Back&...

Finest Regards

**Comment by SGEDA** [comment]
please how can i add more days l try it but there is no result.

**Comment by KrunchMuffin** [comment]
has anyone done this?

**Comment by legreco** [comment]
I have the same problem here. Has anyone find a solution to do this?

**Comment by clevertension** [comment]
#734 add this feature now
