### ISSUE TITLE
iphone5 crash

### ISSUE THREAD

**Issue by mohamedsharaf** [ionic-team/ionic-conference-app#340]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ionic run ios --target "iPhone-5"

the app close instantly unable to open even in any other simulator it works

**Expected behavior:**

ionic run ios --target "iPhone-5" 
run normally in iphone5 ios10.2
**Steps to reproduce:**

**Related code:**

```
ionic run ios --target "iPhone-5"
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by brandyscarney** [comment]
Does it crash if you add the `--prod` flag when running the command?

**Comment by mohamedsharaf** [comment]
confirm error with prod flag
ionic run ios --prod --target "iPhone-5"
ios 8.1
ios 10.2
tested both of them

even i tested the ionic super app its working fine

**Comment by jgw96** [comment]
Hello @mohamedsharaf , unfortunately I cannot reproduce this issue. Does it log any error when it crashes? What version of iOS is your iphone 5 sim running?

**Comment by mohamedsharaf** [comment]
i tested in both version
ios 8.1
ios 10.2

it just close the app and go to home screen

**Comment by mohamedsharaf** [comment]
`
Marker - Jan 12, 2017, 12:08:23 AM
Jan 12 00:08:25 mohameds-MacBook-Pro com.apple.CoreSimulator.SimDevice.B8254F14-CA6C-4CDA-B059-D6E11BA12F50.launchd_sim[883] (UIKitApplication:io.ionic.conferenceapp[0x47be][942]): Program specified by service does not contain one of the requested architectures: Ð^H
Jan 12 00:08:25 mohameds-MacBook-Pro.local SpringBoard[897]: Unable to get pid for 'UIKitApplication:io.ionic.conferenceapp[0x47be]': No such process (err 3)
Jan 12 00:08:25 mohameds-MacBook-Pro.local SpringBoard[897]: Application 'UIKitApplication:io.ionic.conferenceapp[0x47be]' exited voluntarily.
Jan 12 00:08:25 mohameds-MacBook-Pro com.apple.CoreSimulator.SimDevice.B8254F14-CA6C-4CDA-B059-D6E11BA12F50.launchd_sim[883] (UIKitApplication:io.ionic.conferenceapp[0xb16f][943]): Program specified by service does not contain one of the requested architectures: Ð^H
Jan 12 00:08:25 mohameds-MacBook-Pro.local SpringBoard[897]: Unable to get pid for 'UIKitApplication:io.ionic.conferenceapp[0xb16f]': No such process (err 3)
Jan 12 00:08:25 mohameds-MacBook-Pro.local SpringBoard[897]: Application 'UIKitApplication:io.ionic.conferenceapp[0xb16f]' exited voluntarily.
Jan 12 00:08:25 mohameds-MacBook-Pro.local SpringBoard[897]: Unable to deliver -[UIRemoteApplication showTopMostMiniAlertWithSynchronizationPort:] message to port 0: (ipc/send) invalid destination port
 
`

**Comment by brandyscarney** [comment]
@mohamedsharaf I was able to reproduce this on the same target. If you run it through xCode does it work for you too?

**Comment by mohamedsharaf** [comment]
yes i got the same error through xcode
but i have no idea what is this :)

**Comment by brandyscarney** [comment]
@mohamedsharaf So the app doesn't work if you open it up through xCode and run it on the iPhone 5 simulator? Or it does?

**Comment by mohamedsharaf** [comment]
no it does not work

**Comment by mohamedsharaf** [comment]
if founded this comment about similar issue 

you must launch your app in a 64-bit capable simulated device. iPad Retina, iPad 2, iPhone 4S and iPhone 5 are all 32-bit only. You need to launch a iPhone-5s, iPhone-6, iPhone-6-Plus or iPad-Air if you want to test your app in 64-bit mode. 

i will test in real iphone5 soon and will update

**Comment by pscott-au** [comment]
feels like a resource thing - my iphone 6 crashed on startup in xcode - eventally i could launch form the device ok after i killed off a few other apps - are there big resource requirements?

**Comment by mohamedsharaf** [comment]
i dont think its resource i am waiting iphone 5 device to test on it and i will post updates

**Comment by djereg** [comment]
Any updates? It still crash on simulated iPhone 5 device. iOS version 10.3

**Comment by mohamedsharaf** [comment]
i will do my best tp test ionic3 tomorrow and post u update

**Comment by djereg** [comment]
But on simulated iPhone 5s it works, iOS 10.3

**Comment by mohamedsharaf** [comment]
yes it works fine in 5s simulator and also works in 5s device 
but i dont have chance yet to have iphone5 to try the device

**Comment by PhilTheNet** [comment]
Same problem for me, all projects cordova build with Ionic or just BlankCordova template crash with 5 simulator and fine with 5s and >
Log of simulator : Program specified by service does not contain one of the requested architectures
But works by directly compiling from xcode
