### ISSUE TITLE
App crash on Windows 10 when activating map view

### ISSUE THREAD

**Issue by mpaland** [ionic-team/ionic-conference-app#348]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
App crashes when clicking (navigate to) the map either via menu item or via tab.

**Expected behavior:**
Display the map.

**Steps to reproduce:**
Lastest (18/01/2017) conference app.
ionic platform add windows
ionic run windows --prod
Click on the "map" item in tabbar.

Maybe this issue is (more) related to the inappbrowser, crosswalk or the wkwebview.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5-201701112208
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by mhartington** [comment]
Hi there! Im unable to replicate this issue using the latest version of the conference app. I'm going to close it, but if you're still running into issues, please open a new issue.
