### ISSUE TITLE
Live demo?

### ISSUE THREAD

**Issue by kienpham2000** [ionic-team/ionic-conference-app#388]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

There's no live demo link
**Expected behavior:**

There should be a live demo link to play with the app in browser? I'm thinking creating a www build and creating the gh-pages branch?
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mautematico** [comment]
I think https://jgw96.github.io/ionic-conference-app/www/ is maintained by @jgw96

**Comment by jgw96** [comment]
Hello all! I fixed this with this commit.
