### ISSUE TITLE
Update README.md to explain how to deploy to all platforms (web, iOS, Android).

### ISSUE THREAD

**Issue by kodayashi** [ionic-team/ionic-conference-app#389]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

Nice that you have a PWA example! It would be nice if the readme had some steps on how to deploy, especially for web as that's a relatively new concept for ionic.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kodayashi** [comment]
`ionic platform add browser` then `ionic build browser --prod` did the trick (assuming an `npm install first`

**Comment by jgw96** [comment]
Hello all! I fixed this with this commit https://github.com/ionic-team/ionic-conference-app/commit/80063ddeec3d93059ed2892e43b8accbdba0c40e
