### ISSUE TITLE
Failed when trying add platform iOS

### ISSUE THREAD

**Issue by qiluo** [ionic-team/ionic-conference-app#406]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Just clone the source minutes ago, then I ran 'npm i' and 'ionic cordova platform add ios', at the end I got 
```
--save flag or autosave detected
Saving ios@~4.3.1 into config.xml file ...
✖ Copying default image resources into ./resources/ios - failed!
Error: /Users/qiluo/Dev/ionic-apps/ionic-conference-app/node_modules/@ionic/cli-plugin-cordova/dist/resources.json not found
```
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.1
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : not installed
    ios-sim    : 5.0.13

```

**Comment by xupea** [comment]
@qiluo please try:
```
ionic platform add ios
```

**Comment by qiluo** [comment]
@xupea, not worked
```
→ ionic platform add ios
The platform command has been renamed. To find out more, run:

  ionic cordova platform --help
```

**Comment by brandyscarney** [comment]
I'm not able to reproduce this using the latest of the conference app:

```
--save flag or autosave detected
Saving ios@~4.4.0 into config.xml file ...
✔ Copying default image resources into ./resources/ios - done!
```

Please try cloning a fresh copy of the conference app and doing a fresh `npm install`. You may also want to update your ionic CLI to the latest release: `3.4.0`. 

If you are still having problems with this please create an issue on the Ionic CLI repository since it isn't specific to the conference app: https://github.com/ionic-team/ionic-cli/issues

Thank you!
