### ISSUE TITLE
 Removing <ion-grid> breaks conference-app

### ISSUE THREAD

**Issue by mautematico** [ionic-team/ionic-conference-app#412]
**I'm submitting a ...**  (check one with "x")
[*] bug report

**Current behavior:**
Not using ionic-grid breaks this app.

**Expected behavior:**
This app should work even if not using ionic-grid.
Alternatively, it should be described in the docs that using ionic-grid is required, or steps to remove it without breaking conference-app

**Steps to reproduce:**
Clone this repo at 6656291cc7248a6b16dbb380ac1932630b9fa00a
remove src/pages/speaker-list and src/pages-speaker-detail
remove all references to both pages/components from app.module and app.component

ionic serve will still build app in development mode;
howerever, `ionic cordova build browser --prod --release` and `ionic cordova build android --prod --release` won't, because `sass` error ($grid-breakpoints is undefined)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : browser 4.1.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : Linux 4.9
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

Ugly patch:
Insert any code that uses grid, like this one, on any page component:
```
  <ion-grid fixed>
    <ion-row align-items-stretch>
      <ion-col col-12 col-md-6 align-self-stretch align-self-center approxItemHeight="457px">
      </ion-col>
    </ion-row>
  </ion-grid>
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce this using the latest version of the conference app. If you are still running into this after cloning and running `npm install`, please let me know and I'll take another look. Thanks! :smile:
