### ISSUE TITLE
Favorite not saved

### ISSUE THREAD

**Issue by guilhermeof** [ionic-team/ionic-conference-app#414]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When selecting an item for a favorite, it is lost when you exit and enter the application again, so every time the item that was selected as a favorite is lost when updating.

**Expected behavior:**

The favored item is expected to be permanently saved in the app, unless the user wants to delete the favorite item

**Steps to reproduce:**

1. git clone project

2. cd project

3. npm install

4. ionic serve 

**Related code:**

```
addFavorite(slidingItem: ItemSliding, sessionData: any) {

    if (this.user.hasFavorite(sessionData.name)) {
      // woops, they already favorited it! What shall we do!?
      // prompt them to remove it
      this.removeFavorite(slidingItem, sessionData, 'Favorite already added');
    } else {
      // remember this session as a user favorite
      console.log(sessionData.name);
      this.user.addFavorite(sessionData.name);


      let toast = this.toastCtrl.create({
        message: 'Adicionado como favorito',
        duration: 3000,
        position: 'middle',
      });

      slidingItem.close();

      // now present the alert on top of all other content
      toast.present();
    }

  }
```

**Other information:**
https://forum.ionicframework.com/t/persistent-data-with-no-user-session/88715

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.3.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : Linux 4.11
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is happening simply because we have not implemented this functionality. If this was not just a demo app and was a real app this functionality would make sense, but since this is just a showcase of ionic components we have not built this functionality.
