### ISSUE TITLE
Uncorrect switching to the hidden tab

### ISSUE THREAD

**Issue by Smoke1987** [ionic-team/ionic-conference-app#417]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hello everybody. The problem is the following: in the application (Ionic 2) the Tabs component is used. In a single component, one of the child Tabs is hidden (not displayed on the tab-bar). There is a right-hand menu, from which switching proceeds by way of `this.nav.setRoot(page.name, params).catch` where the parameter passes the index of the hidden tab. Switching occurs on the first not hidden tab. However, when you switch, when the current Nav is already a component with the tabs, it is correct (`this.nav.getActiveChildNav ().select (page.index)` - switches to the hidden tab). Any idea how to solve this?

**Expected behavior:**
Correct switch to the hidden tab.

**Steps to reproduce:**
--

**Related code:**

```
<ion-tab [root]="tab2Root" tabTitle="Офисы продаж" tabIcon="globe" show="false"></ion-tab>
this.nav.setRoot(page.name, {tabIndex: 1}).catch
this.nav.getActiveChildNav().select(page.index)
```

**Other information:**
--

**Ionic info:**

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the conference app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about using the framework. :smile:

Thanks so much!
