### ISSUE TITLE
Card CSS glitch on the Chrome Browser.

### ISSUE THREAD

**Issue by snowyu** [ionic-team/ionic-conference-app#426]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The cards of speaker are overlap together on one line.

**Expected behavior:**

It should be not overlap.

**Steps to reproduce:**
<!-- If you are able to illustrate the bug or feature request with an example, please provide steps to reproduce and if possible a demo using the following template:

1. click [try it live](https://ionic-team.github.io/ionic-conference-app/www) on the chrome browser.
2. click the `Speaker`
3. resize the width of the window greater than 1720

**Comment by mg1075** [comment]
I see the the issue in Chrome, and in Microsoft's Edge browser, the issue is more pronounced.

Here is a screenshot from Chrome:
![image](https://user-images.githubusercontent.com/2031435/29141502-1cbdae0c-7d14-11e7-98f6-6cdc79f1fb7c.png)
