### ISSUE TITLE
Cannot read property 'select' of undefined

### ISSUE THREAD

**Issue by lvncnt** [ionic-team/ionic-conference-app#429]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
```
Runtime Error: Cannot read property 'select' of undefined
Stack
TypeError: Cannot read property 'select' of undefined
    at ConferenceApp.webpackJsonp.280.ConferenceApp.openPage (http://localhost:8100/build/main.js:1437:45)
    at Object.eval [as handleEvent] (ng:///AppModule/ConferenceApp.ngfactory.js:41:24)
    at handleEvent (http://localhost:8100/build/vendor.js:12273:138)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:13565:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/vendor.js:13153:12)
    at dispatchEvent (http://localhost:8100/build/vendor.js:9173:21)
    at http://localhost:8100/build/vendor.js:9765:20
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/vendor.js:33653:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37)
```
**Steps to reproduce:**
1. run ```ionic serve```
2. click Schedule tab
3. click Login tab
4. click Schedule tab again 

**Related code:**
https://github.com/ionic-team/ionic-conference-app/blob/master/src/app/app.component.ts
Line 109: ```this.nav.getActiveChildNavs()[0].select(page.index);```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
$ ionic info

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.5.3
```
Works fine for ```Ionic Framework : ionic-angular 3.3.0```

**Comment by AmanHanjra** [comment]
Same issue with me also.
Please solve this Ionic Team.

**Comment by brandyscarney** [comment]
Fixed by https://github.com/ionic-team/ionic-conference-app/pull/428, please pull latest. Thanks!

**Comment by DuaneQ** [comment]
@brandyscarney I'm not sure how to implement this solution.

This is when a user initially logs in:

`  async nativeGoogleLogin(): Promise<void> {
    try {
      const gplusUser = await this.gPlus.login({
        'webClientId' : '920843394799-agr1ul1hadm3bnl2f8bgmlgq6agjln95.apps.googleusercontent.com',
        'offline' : true,
        'scopes' : 'profile email'
      })

      return await this.afAuth.auth.signInWithCredential(
        firebase.auth.GoogleAuthProvider.credential(gplusUser.idToken)
      ).then(() =>{
          this.navCtrl.parent.select(2);
      })
    } catch(err){
      console.log(err);
    }
  }`

And I get the error 'Cannot read property select of null'.

If I close and re-open I can then navigate.

I added the following to app.component.ts per the example:

`  appPages: PageInterface[] = [
    { title: 'Popular', name: 'TabsPage', component: TabsPage, tabComponent: PopularPage, index: 0, icon: 'star-outline' },
    { title: 'Matching', name: 'TabsPage', component: TabsPage, tabComponent: MatchesPage, index: 1, icon: 'mail' },
    { title: 'Settings', name: 'TabsPage', component: TabsPage, tabComponent: HomePage, index: 2, icon: 'settings' },
  ];`

`  openPage(page: PageInterface) {
    let params = {};

    // the nav component was found using @ViewChild(Nav)
    // setRoot on the nav to remove previous pages and only have this page
    // we wouldn't want the back button to show in this scenario
    if (page.index) {
      params = { tabIndex: page.index };
    }

    // If we are already on tabs just change the selected tab
    // don't setRoot again, this maintains the history stack of the
    // tabs even if changing them from the menu
    if (this.nav.getActiveChildNavs().length && page.index != undefined) {
      this.nav.getActiveChildNavs()[0].select(page.index);
    // Set the root of the nav with params if it's a tab index
  } else {
      this.nav.setRoot(page.name, params).catch((err: any) => {
        console.log(`Didn't set nav root: ${err}`);
      });
    }
  }`


And the following to the tabs page:

`        this.mySelectedIndex = navParams.data.tabIndex || 0;
`
