### ISSUE TITLE
Android building and emulating don't work

### ISSUE THREAD

**Issue by razzdrawon** [ionic-team/ionic-conference-app#430]
Im trying to emulate or build directly to an android device or emulator and when run:
"ionic cordova build android" it works and says "BUILD SUCCESSFUL" but when I try installing in a device it fails.

Also when I run "ionic cordova emulate android", it bring the emulator to the front and starts an app but it stays in blank.

Can anybody help me?

My ionic info:

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v7.10.0
    OS         : OS X El Capitan
    Xcode      : Xcode 8.0 Build version 8A218a 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.8 
Steps to reproduce:

Running starter command line for conference app
ionic start test conference
then add android platform with:

npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
ionic cordova platform add android
Then run

ionic cordova emulate android
ionic cordova build android
Everything seems to be fine until here... emulate and build were successful but when the emulator comes up and launch the app, it looks like

<img width="464" alt="252aa002-4657-11e7-8bae-4b3048fc0d5c" src="https://user-images.githubusercontent.com/4486150/28430118-e9a0121e-6d44-11e7-9dcd-1fc39d274227.png">

And trying to install the apk generated in the build command, it fails in many devices I have tried.

For iOS everything goes fine and also working with other starters projects, android works good.

Thanks for your help,
Regards

**Comment by shy001** [comment]
Im having an issue related to this - It runs on the emulator but not on my device - error received
Using cordova-fetch for cordova-ios@4.5.2
Error: Failed to fetch platform cordova-ios@4.5.2
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.

--note I dont want to run the ios version, just android but I get this

**Comment by nedssteven** [comment]
I have the same problem !!!!

**Comment by brandyscarney** [comment]
Please try running the following prior to the `emulate/build` commands:

```
rm -rf platforms plugins && cordova prepare
```

If you're still running into issues please search/ask on our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for faster assistance. 🙂
