### ISSUE TITLE
remove crosswalk as it reached end of life

### ISSUE THREAD

**Issue by mohamedsharaf** [ionic-team/ionic-conference-app#434]
it add extra 20mb space and webview is now auto-updated with android 
-----------------------------------------------------------
When Intel started the Crosswalk Project in 2013, our goal was to bring the full power of the web platform to mobile and desktop application developers. Since then, the environment has evolved and Progressive Web Apps bring the power of native apps to pure web applications. Now, the Android platform Webview shares code and features with the Chrome browser and is kept up-to-date, while Electron and Intel’s NW.JS support most desktop developers. As a result, we believe Crosswalk has done its job and we can make a bigger impact focusing on other areas of the web platform.

Crosswalk 23 is our last stable release. After that we will no longer fix specific bugs but will leave the source code and binaries available for Crosswalk users to continue building applications. We welcome help from the Crosswalk community and would not discourage anybody willing to maintain the project.

We value your contributions and involvement with Crosswalk. The Open Source Technology Center Web Technology team at Intel will continue to drive adoption of new web technologies in new areas, and we look forward to introducing new projects that will drive the web platform forward.

Thank you for using Crosswalk!
https://crosswalk-project.org/blog/crosswalk-final-release.html

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by pwespi** [comment]
There is an open PR #432 about this.
