### ISSUE TITLE
Init Loading Speed is very slow

### ISSUE THREAD

**Issue by jyyblue1987** [ionic-team/ionic-conference-app#437]
[ ] feature request

**Current behavior:**
When app is build and run on android, after splash is shown, first page is displayed after 10s.

**Expected behavior:**
I want to see first page at 2 ~ 3s.

**Steps to reproduce:**
npm install
ionic state reset
ionic cordova platform android
ionic cordova run android

**Comment by pwespi** [comment]
Try `ionic cordova run android --prod`.

**Comment by zcxzmzy** [comment]
me too,I also face this problem,can you tell us how to deal with it?
