### ISSUE TITLE
feature request: include another language option with angular translate

### ISSUE THREAD

**Issue by mg1075** [ionic-team/ionic-conference-app#438]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
At present, the app is only in English.

**Expected behavior:**
A nice feature for the conference app would be the inclusion of angular translate and the ability to switch between at least English and one other language.

**Other information:**
- https://ionicframework.com/docs/developer-resources/ng2-translate/
- https://forum.ionicframework.com/t/ngx-translate-and-ionic-3/87005/28

**Comment by pwespi** [comment]
For an example implementation of ngx-translate in ionic you can also take a look at the [super starter](https://github.com/ionic-team/ionic-starter-super#i18n).
