### ISSUE TITLE
when it run at android fax machine Instead of simulator,it looks so ugly?can you tell me why?

### ISSUE THREAD

**Issue by zcxzmzy** [ionic-team/ionic-conference-app#440]
when it run at android fax machine Instead of simulator,it looks so ugly?can you tell me why

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the conference app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the conference app, please create a new issue with answers to the pre-populated questions:

<img width="694" alt="screen shot 2017-01-19 at 3 19 46 pm" src="https://cloud.githubusercontent.com/assets/6577830/22123735/c61e8de4-de5a-11e6-85dd-763277b0ad86.png">

Thanks so much!
