### ISSUE TITLE
where can I download this demo to install in my Android phone？

### ISSUE THREAD

**Issue by jake2009** [ionic-team/ionic-conference-app#450]
where can I download this demo to install in my Android phone？
I just wanna have a try

**Comment by Rattone** [comment]
Here you can find a demo, it's a web version that is browser (desktop/mobile) compatible:
http://ionic-team.github.io/ionic-conference-app/www/

**Comment by jjjhanreyyy** [comment]
@jake2009  You could download Ionic DevApp on your Android Phone. Connect your Android phone and PC/Mac within the same network. Serve the app and you can now view the app. You could also modify the app and it will be live reloaded.

**Comment by brandyscarney** [comment]
You can run the following to clone this app:

`ionic start "Conference App" https://github.com/ionic-team/ionic-conference-app.git`

For more information on deploying, see our docs: https://ionicframework.com/docs/intro/deploying/

Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) if you have more questions. 🙂
