### ISSUE TITLE
To change the background color and color in css file

### ISSUE THREAD

**Issue by vigneshrvicky** [ionic-team/ionic-conference-app#457]
How to change  the background color and colors in css file(main.css). If I change the color it will done perfectly.but when i restart the server(ionic serve) it will noting changed,the color didn't change

**Comment by brandyscarney** [comment]
Thanks for the issue! Ionic uses [Sass](http://sass-lang.com/) to create the css file, so every time you run a build the css file will be overwritten. Take a look at our documentation on theming here: 

- http://ionicframework.com/docs/theming/theming-your-app/
- http://ionicframework.com/docs/theming/sass-variables/
- http://ionicframework.com/docs/theming/overriding-ionic-variables/

If you have more question on using the framework, please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/). :smile:
