### ISSUE TITLE
Twitter account login

### ISSUE THREAD

**Issue by vigneshrvicky** [ionic-team/ionic-conference-app#459]
When I click the speaker tab,its shows tweet,share,contact links in ionic conference app master.In that if i click the tweet link,i need to tweet using my twitter account.

I changed the  title "username" as "twitter Id" in login and sign up pages.

Now when users login or signup using their tweeter id.In speaker Tab,by clicking the tweet link,they need to tweet using their twitter account.The page  will automatically goes to user twitter account

And also if i click the share link then it will automatically share in users twitter account

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the conference app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the conference app, please create a new issue with answers to the pre-populated questions. Thanks so much!

**Comment by vigneshrvicky** [comment]
ya its not an issues,but i need this

I changed the title "username" as "twitter Id" in login and sign up pages.

Now when users login or signup using their tweeter id.In speaker Tab,by clicking the tweet link,they need to tweet using their twitter account .I mean,The page will automatically goes to user twitter account.From their account they can post the tweet.

And also if i click the share link then it will automatically share in users twitter account
