### ISSUE TITLE
when clicking the tweet,its goes to https://twitter.com/ionicframework, i need to change from ionicframework into other how?

### ISSUE THREAD

**Issue by vigneshrvicky** [ionic-team/ionic-conference-app#460]
when clicking the tweet in speaker tab,its goes to https://twitter.com/ionicframework, i need to change from ionicframework into other. how?

**Comment by mhartington** [comment]
Hi there! This doesn't appear to be an issue with the framework it self, so I'm going to close it. Please post your question on the [Ionic Forum](https://forum.ionicframework.com) instead.
