### ISSUE TITLE
where the users entered data saved

### ISSUE THREAD

**Issue by vigneshrvicky** [ionic-team/ionic-conference-app#462]
In ionic2-form-handling-and-validations-master,where the users entered data saved?

i entered username,lastname,country,email,password,confirm password and then i click the submit button

but i dont know where(in which location) these entered data saved?

**Comment by mhartington** [comment]
Hi there! This doesn't appear to be an issue with the framework it self, so I'm going to close it. Please post your question on the [Ionic Forum](https://forum.ionicframework.com) instead.
