### ISSUE TITLE
Splash Screen is not displayed when requesting permissions

### ISSUE THREAD

**Issue by blver** [ionic-team/ionic-conference-app#466]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When the permissions are being asked at the first run, in Android, there is no splash screen afterwards.

Splash screen exists when running the app again afterwards.

For the purpose of the following video the Filepath plugin was installed that requests for:
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Expected behavior:**

Even when permissions are asked, the splash screen should follow.

**Steps to reproduce:**

$ ionic cordova plugin add cordova-plugin-filepath
$ npm install --save @ionic-native/file-path

And then 
$ ionic cordova build android

[Related Video](https://www.youtube.com/watch?v=2ZKEKnLu4t8&feature=youtu.be)

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\eirwn\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0 windows 5.0.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.0
    npm               : 3.10.10
    OS                : Windows 10
```

**Comment by debasiskar-devel-007** [comment]
have you came accross  any solution ?

**Comment by blver** [comment]
No we are going with it being blank on the first run but it is ugly.
Let's hope someone will address it soon.

**Comment by bollatialfredo** [comment]
Same issue here, any updates?
