### ISSUE TITLE
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

### ISSUE THREAD

**Issue by mikemichaelis** [ionic-team/ionic-conference-app#470]
[x ] bug report

Note "ionic start test blank" and "super" work just fine.  "ionic start test conference" works when using "ionic serve" but trying to run on device or emulator fails with:

**Current behavior:**
> cordova emulate android
ANDROID_HOME=/home/mike/Android/Sdk
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
Subproject Path: CordovaLib
null

The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

	at build_5zuinex01yt6w4n27pf6xfeka.run(/home/mike/Git/minder2/platforms/android/build.gradle:142)

org.xwalk:xwalk_core_library:22+
Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.

FAILURE: Build failed with an exception.

* What went wrong:

A problem occurred configuring root project 'android'.

> 
All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

**Expected behavior:**

**Steps to reproduce:**
Formatted laptop
installed ubuntu 16.04.03
node 8.9.4
npm 5.6.0
Android Studio 3.0.1
ionic 3.19.1
openjdk 1.8.0_151

ionic start minder2 conference
ionic cordova platform add android

~/Android/Sdk/tools emulator -avd default // previously created in Android Studio and starts emulator

ionic cordova emulate android

insert the output from ionic info here
```
cli packages: (/home/mike/.nvm/versions/node/v8.9.4/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /home/mike/Android/Sdk

Misc:

    backend : pro

**Comment by mikemichaelis** [comment]
I still cannot get this working on my fresh Ubuntu 16.04 laptop.  So I tried it at work on my dev desktop and it works!  I still get the errors, but it continues to deploy to the device and execute.

> cordova run android
[10:12:11]  lint finished in 2.67 s
ANDROID_HOME=C:\Android\Sdk
JAVA_HOME=D:\Java\jdk1.8.0_151
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

:wrapper


BUILD SUCCESSFUL in 6s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

null
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_1jzexuq3i5q3q1s6rkrb97p82.run(C:\Git\conference\platforms\android\build.gradle:138)
org.xwalk:xwalk_core_library:22+

The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.

The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.

:preBuild UP-TO-DATE

insert output of ionic info here

cli packages: (C:\Users\NB52213\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.2.3 ios 4.5.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    Node              : v6.9.1
    npm               : 3.10.8
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Android\Sdk

Misc:

    backend : pro

**Comment by mikemichaelis** [comment]
I noticed the only different in the two systems is the laptop is using android@6.4.0 and desktop is using android@6.2.3.

<on desktop>
ionic cordova platform remove android
ionic cordova platform add android@6.4.0

The build now fails as it does on my laptop.

It's clear this seed has an issue with with cordova platform android@6.4.0

this line in config.xml needs to be updated

<engine name="android" spec="^6.2.3" /> -> <engine name="android" spec="6.2.3" />

or to the latest android platform that works.

Thanks,
Mike

**Comment by mikemichaelis** [comment]
I verified this solution works on my laptop dev environment.  To fix I executed

ionic start conference conference
cd conference
npm install cordova-android@6.2.3 --save-exact
ionic cordova prepare
ionic cordova run android

Works great!  Thanks!  

I hope this helps somebody.

**Comment by mesmail** [comment]
Thanks so much it's works for me also

**Comment by erperejildo** [comment]
so it doesn't work with latest version?

**Comment by zubliquzaini** [comment]
@erperejildo I guess so.. spend the last 2 days fixing crosswalk error. Thanks @mikemichaelis ! :)

**Comment by Harivinoth** [comment]
Hi Friends,
   
    Right now my cordova project android version 5.1.1. In my project "cordova-plugin-file" and "cordova-plugin-file-transfer" was not supported. So we had updated android version 6.3.0 . After that tried to install "cordova-plugin-file" and "cordova-plugin-file-transfer" we got the below issues



Installing "cordova-plugin-file-transfer" for android
Plugin dependency "cordova-plugin-file@6.0.1" already fetched, using that version.
Installing "cordova-plugin-file" for android
ANDROID_HOME=/Users/jaiganesh/mobile/android-sdk-macosx
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_2q9f6armj2p9h1ex9dp6tezvs.run(/Users/jaiganesh/Documents/spotandpay/platforms/android/build.gradle:142)
Checking the license for package Android SDK Platform 26 in /Users/jaiganesh/mobile/android-sdk-macosx/licenses
Warning: License for package Android SDK Platform 26 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 26].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.704 secs
Failed to install 'cordova-plugin-file': Error: /Users/jaiganesh/Documents/spotandpay/platforms/android/gradlew: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/jaiganesh/Documents/spotandpay/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Failed to install 'cordova-plugin-file-transfer': Error: /Users/jaiganesh/Documents/spotandpay/platforms/android/gradlew: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/jaiganesh/Documents/spotandpay/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: /Users/jaiganesh/Documents/spotandpay/platforms/android/gradlew: Command failed with exit code 1

**Comment by danjimgar** [comment]
You have to accept the license:

https://stackoverflow.com/questions/40383323/cant-accept-license-agreement-android-sdk-platform-24/40383457#40383457

**Comment by danielesalazars** [comment]
Tengo el mismo error pero no lo puedo arreglar con nada, por favor orienten bien para la solucion.

**Comment by danieldocumentos** [comment]
Me funcionó esto: ionic cordova run android

**Comment by brandyscarney** [comment]
Thanks for the issue! Please run the following command to get the latest cordova-android if you are still seeing this:

```
rm -rf platforms plugins && cordova prepare
```

**Comment by AamirAlam** [comment]
Most of the build problems has been solved by running the following cammand
`cordova clean android`
`cordova build android`
