### ISSUE TITLE
Issues with v4

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-conference-app#473]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

General issues
- [x] `<ion-page>` is required as a wrapper for all pages now - **Removing requirement from core**
- [x] Google Maps API error
- [x] Back button is black (`md`) and primary (`ios`) instead of white on a color toolbar
- [x] Menu button is showing with the back button
- [ ] Swipe-to-go-back is not right. Does not follow 1:1, but just listens for gesture start

Stencil issues
- [x] do not require stencil/core dep
- [x] do not require ionicons dep
- [x] remove ion-events
- [x] onWillDismiss is not getting data passed back
- [x] `ERROR TypeError: element.componentOnReady is not a function` is thrown randomly
- [x] dispatch "appinit" and "appload" events
- [ ] expose namespaced raf
- [ ] expose namespace addEventListener

Pages
- [x] Schedule - Segment is not automatically selecting the default value and clicking between it isn’t changing the list items
- [x] Schedule - Search is not filtering items
- [x] Schedule - the favorite item option is not the right color
- [x] Schedule - the bars on the left are not there
- [x] Schedule - fab button missing
- [x] Schedule - no list items found is missing
- [x] Schedule - fab list buttons are not colored
- [x] Schedule filter - Toggles in modal are not there
- [x] Schedule filter - Header is not primary on Android
- [x] Map - the map is not visible
- [x] Map - tab icon looks off centered
- [x] About - Date is not populated 
- [x] About - Clicking support throws `ERROR Error: Uncaught (in promise): Error: No component factory found for SupportPage. Did you add it to @NgModule.entryComponents?`
- [x] About - Clicking on Date shows an orange focus border
- [x] About - Header image on page is not showing (404)
- [x] Login - Icon is too large
- [x] Login - Login / Signup buttons do not work
- [x] Login - Wrong button styles
- [x] Support - icon is too large
- [x] Support - Submit button doesn’t work
- [x] Support - header image is not loading correctly
- [x] Sign up menu item - throws an error with URL segment
- [x] Tutorial is not working
- [x] Tutorial page skip button does not navigate
- [x] About - Clicking the backdrop to close popover throws an `overlay is not presented` error
- [x] Schedule - activating fab button/list requires setting activated
- [x] Login/Signup/etc - the input focus is showing with no lines
- [x] Schedule - the searchbar icon isn't showing
- [x] Menu - some icons for the support pages aren't showing
- [x] Tutorial - Clicking Show Tutorial from the menu navigates back to Schedule
- [x] Navigation - Clicking on a speaker/schedule and then switching to a different tab and back brings to the main list
- [x] Speaker Detail - Lines are showing on the first item (https://github.com/ionic-team/ionic/issues/15185)

ionic/angular
- [ ] NavController, NavParams, Platform, App, MenuController need to be `@Injectable`

**Comment by mhartington** [comment]
>Google Maps API error

We need to supply a google Map API key for this.

**Comment by ryanhalley** [comment]
I'm hitting this issue now. Hosted app on http for a quest test, map is fine, then host on https and no map; no problem adding an API key but how to do so? I'm familiar with google maps access via a native plugin in config.xml, but I'm still reading up on PWA and it's equivalent support, so not sure yet where that gets configured?

**Comment by mhartington** [comment]
Tutorial has been added, needs to be cleaned up after navigation/routing is done
