### ISSUE TITLE
missing script: serve when running ionic serve

### ISSUE THREAD

**Issue by llvc** [ionic-team/ionic-conference-app#475]
I cloned this git and run `ionic serve` after `npm install`.
But it says `missing script: serve`
The `ionic info` is:
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 3.9.2
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 3.1.5
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v8.9.0
Xcode version: Xcode 9.0.1 Build version 9A1004
```

Error is:
```
npm ERR! missing script: serve
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-conference-app@0.0.0 ionic:serve: `npm run serve "--address" "192.168.12.230" "--v2" "undefined" "--port" "8000" "--livereload-port" "35729"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-conference-app@0.0.0 ionic:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
There was an error serving your Ionic application: There was an error with the spawned command: serve
```
I need a help

**Comment by brandyscarney** [comment]
Can you please try updating the Ionic CLI? The latest version is `3.19.1`:

```
npm uninstall -g ionic
npm install -g ionic
ionic -v
```

The last command should print out `3.19.1`. Let me know if that fixes it!

**Comment by llvc** [comment]
@brandyscarney 
Thanks for your help.
It is resolved

**Comment by SharpFu** [comment]
I need you help also,

> npm ERR! missing script: serve

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sharpfu\AppData\Roaming\npm-cache\_logs\2018-03-19T08_28_07_357Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-conference-app@0.0.0 ionic:serve: `npm run serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-conference-app@0.0.0 ionic:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:



I think the package.json 's scripts need a script "serve":"ionic-app-scripts serve" as the same of "build",when i add it to ,but can't run also.

**Comment by geralch** [comment]
I have the same error but when I run `npm start` runs normally 😐
