### ISSUE TITLE
Testing Ionic 4 - Ion slides positioning problem

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-conference-app#483]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Relates to 
Issues with v4 #473
Tutorial page skip button does not navigate

The ion slides positioning is not good.

**Expected behavior:**
Pictures/text should not show in the slide indicators.
Seems to work in lab view but not in browsers.

**Steps to reproduce:**
Run ICA core-update.
Screen resolution 1600x900
![capture298](https://user-images.githubusercontent.com/140737/39167875-47701688-4746-11e8-8742-43f161b278c8.png)

**Related code:**

```
insert any relevant code here
```

**Other information:**
https://github.com/ionic-team/ionic/issues/14315

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
C:\ae\aedev\ionic-conference-app>ionic info
cli packages: (C:\Users\peter\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.5
   ionic (Ionic CLI) : 4.0.0-rc.5

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @angular-devkit/core       : 0.5.7
   @angular-devkit/schematics : 0.5.7
   @angular/cli               : 6.0.0-rc.3
   @ionic/schematics-angular  : 1.0.0-rc.5
   Cordova Platforms          : none
   Ionic Framework            : @ionic/angular 4.0.0-alpha.3

System:

   NodeJS : v8.11.1
   npm    : 5.8.0
   OS     : Windows 10

Environment Variables:

   ANDROID_HOME : not set


C:\ae\aedev\ionic-conference-app>
```

**Comment by trainingnote** [comment]
I got a problem too with the slide content not being well set, I used the same style and same markup as for the demo app here is what I get :
![screenshot from 2018-05-26 09-57-54](https://user-images.githubusercontent.com/30081782/40574045-7995fb7a-60cb-11e8-9295-c4e98c968f15.png)

```
local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : android 7.0.0
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7


```

**Comment by MrSparklle** [comment]
As workaround you can put the slide content inside a `<ion-label>` tag:

```
<ion-slide>
      <ion-label>
        <img src="assets/imgs/slidebox-img-1.png" class="slide-image" />
        <h2 class="slide-title">
          <b>Welcome</b>
        </h2>
        <p text-wrap>
          text text text text text 
        </p>
        <p>
          <img src="assets/imgs/finger-swipe.svg" class="swipe">
        </p>
      </ion-label>
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm not able to reproduce this on latest, are you still seeing this?
