### ISSUE TITLE
Ionic Conference app Core-update branch not working on device

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ionic-team/ionic-conference-app#563]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Description:**

Ionic 4 app works in android/ios emulator but does not work on android/ios device with command `ionic cordova run android --prod`
It shows a white screen for long time and then says: Application Error (Connection to server was unsuccessfull (file:///android_asset/www/index.html)

**Steps to Reproduce:**

1. Clone ionic conference app (core update branch)
2. Try to run on device with command `ionic cordova run android --prod`

**Output:**

**My `ionic info`:**

```
cli packages: (C:\Users\apatwari\AppData\Roaming\npm\node_modules)

   @ionic/cli-utils  : 2.0.0-rc.5
   ionic (Ionic CLI) : 4.0.0-rc.5

global packages:

   cordova (Cordova CLI) : 6.5.0

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.3
   @ionic/schematics-angular  : 1.0.0-rc.6
   Cordova Platforms          : android 6.4.0
   Ionic Framework            : @ionic/angular 4.0.0-alpha.6

System:

   NodeJS : v9.11.1
   npm    : 5.6.0
   OS     : Windows 7
```

**Other Information:**

![image](https://user-images.githubusercontent.com/5632217/40164368-fe89d4d4-59c1-11e8-8983-c3f651fd6de6.png)

**Comment by touch2hussain** [comment]
Same issue with me on core-update branch !

**Comment by lander854** [comment]
same here

**Comment by uiktiomasfeliz** [comment]
Try to run ```ng build``` and then ```ionic cordova run android --prod```

**Comment by brandyscarney** [comment]
Thanks for the issue! Are you still running into this using the latest on the `master` branch?
