### ISSUE TITLE
【deploy issue】Got a blank page after deployed on iOS simulator.

### ISSUE THREAD

**Issue by victordpg** [ionic-team/ionic-conference-app#664]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

after deployed, just got a blank page as below:
![image](https://user-images.githubusercontent.com/4286838/45856235-4672dc00-bd86-11e8-91f9-79f2dc3602f0.png)
![image](https://user-images.githubusercontent.com/4286838/45856328-95207600-bd86-11e8-9a60-4b3cd5a8ee14.png)

**Expected behavior:**

home page showed on iOS simulator.

**Steps to reproduce:**

run deploy command:
ionic cordova run ios --prod 

**Related code:**

```
current master branch
```

**Other information:**

**Ionic info:

```

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.8
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 5 other plugins)

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Sierra
   Xcode  : Xcode 8.2.1 Build version 8C1002

```

**Comment by leonardgithub** [comment]
any way to avoid this problem temporarily?
