### ISSUE TITLE
goToSessionDetail: method not more useful

### ISSUE THREAD

**Issue by meriturva** [ionic-team/ionic-conference-app#704]
I found on two different pages method `goToSessionDetail` not called anymore.
i guess was used before directly define routing on `ion-item` component on template file.

What do you think to delete it?

Here direct link:

https://github.com/ionic-team/ionic-conference-app/blob/556739da92754f556d7976687f6ae53caced05e7/src/app/pages/speaker-detail/speaker-detail.ts#L36

https://github.com/ionic-team/ionic-conference-app/blob/2628ab1ea02cef228330c03696c9cd9c310bbf77/src/app/pages/schedule/schedule.ts#L68

**Comment by brandyscarney** [comment]
Thanks for the issue! It seems it has since been deleted so I will be closing this, but let us know if you find any more cases of it!
