### ISSUE TITLE
Livereload took 25sec

### ISSUE THREAD

**Issue by clankiPad** [ionic-team/ionic-conference-app#717]
Hi everybody !

**I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] support request

**Expected behavior:**
Livereload took at least 25sec to appear

**Steps to reproduce:**
Run `ng serve` and do some change in your code to genere a livereload

**Other information:**
The problem is not only on RC

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.0.7
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.1

System:

   NodeJS : v8.4.0 (/usr/local/bin/node)
   npm    : 5.3.0
   OS     : macOS High Sierra
```

**Comment by brandyscarney** [comment]
I'm going to close this as there has been no reply in awhile and `ng serve` is an Angular CLI command. Please report issues with the Angular CLI on their repository, thanks!
