### ISSUE TITLE
Tests needed

### ISSUE THREAD

**Issue by AugusDogus** [ionic-team/ionic-conference-app#777]
**I'm submitting a ...** 
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
There is a significant lack of unit tests and e2e tests in this app. For those starting with an app looking for the best practices to go by, many are redirected here to learn and go off of. Right now the Ionic community is pretty barren on how to implement tests for an Ionic 4 project. Community leaders such as Joshua Morony and Simon Grimm have not put out tutorials explaining how to do so yet and I can't find official docs either.

**Expected behavior:**
Have full code coverage of components and a passing e2e test suite.

**Steps to reproduce:**
N/A

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/Users/redacted/.nvm/versions/node/v10.15.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 5 other plugins)

System:

   NodeJS : v10.15.1 (/Users/redacted/.nvm/versions/node/v10.15.1/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61

```

**Comment by splitt3r** [comment]
https://ionicframework.com/docs/building/testing looks good. But you are right complete tests + CI running it would be great 👍

**Comment by brandyscarney** [comment]
Thanks for the issue! I've updated the repository to use Github actions which will now run `ng test` and `ng e2e`. You can see all of them running here: https://github.com/ionic-team/ionic-conference-app/actions

To run the CI locally:

```
npm run e2e -- --configuration=ci
npm run test -- --configuration=ci
```

If anyone would like to help us out with tests it would be greatly appreciated. The guide posted above should help. Thanks! 🙂
