### ISSUE TITLE
Ionic 4 application is not working on Android 5.0, Android 5.1, Android 6.0.

### ISSUE THREAD

**Issue by thesurya9** [ionic-team/ionic-conference-app#801]
Ionic 4 application is not working on Android 5.0, Android 5.1, Android 6.0.

But ionic official claims it will support android 4.4 or greater.
But it’s not working. I m searching for a solution from last week.

I have decided to make an app in Ionic 4. I made very blunders mistake. Now I can not go back. it took me 2 months to develop the app from scratch, I very much disappointed.
Can someone please help me?

**Comment by wilfredonoyola** [comment]
Hi, I seen that this project was updated with new commits, Maybe This was fixed.

**Comment by manucorporat** [comment]
This is a repo for ionic-conference-app, not ionic 4. Ionic works fine in Android 5 and up, since the WebView auto updates, so it should use latest chrome.

Please open a proper issue in the ionic 4 repo, following the issue templates and explaining how to properly reproduce.
